- CHANGELOG
- npm-shrinkwrap.json
@chilts, @dannycoates, @rfk, r? - fixes https://github.com/mozilla/fxa-auth-db-mysql/issues/14 for the train-31 branch
This is a re-generated `npm-shrinkwrap.json` file on the train-31 branch that will use the intended train-31 branch of `fxa-auth-db-server`. (It was generated with `/bin/rm -rf ./node_modules ./npm-shrinkwrap.json ; npm cache clear; npm install; npm -d prune; npm shrinkwrap --dev`, and node 0.10.36 and npm 2.6.1 (latest stable). The prune is something needed because shrinkwrap was complaining about having redundant copies of `bluebird`, `ass` and `tap` and refusing to write a new `npm-shrinkwrap.json` file. (Given that it was a clean `npm install`, it seems odd that `npm shrinkwrap` was unhappy with the result, but anyways...).
So, besides putting the installed …
> fix(shrinkwrap): [train-31] regenerated npm-shrinkwrap.json that uses the correct version of fxa-auth-db-server

- package.json
completely trivial, but annoying `npm WARN package.json fxa-auth-db-mysql@0.32.0 No bin file found at db_patcher.js`
> chore(npm): npm warning about 'No bin file found at db_patcher.js'

- db/mysql.js
- db/patch.js
- db/schema/patch-008-009.sql
- db/schema/patch-009-008.sql
- test/local/event_log.js
- test/local/mysql_tests.js
Here's an idea that @dannycoates and I have been kicking around, for how the auth-server might interact with the upcoming notification server (https://github.com/mozilla/fxa-notification-server).
The idea here is to transactionally track our major account-lifecycle events in the database.  There's a simple "eventLog" table to which we append create, verify, reset and delete events as they happen, with an auto-increment sequence number to ensure they're stored properly and consistently ordered.
When the notification server is ready, some background process in the server can read from this queue and schlep the events on over there asynchronously.  Details of that TBD but I added a couple of the low-level functions it'll probably need.
The advantage of this approach is that we won't lose …
> Explicitly track account lifecycle events in the db

- db/mysql.js
- npm-shrinkwrap.json
- package.json
Since the fxa-auth-server always sends these fields, then we shouldn't
set them to anything in this backend.
Fixes #12 - Be consistent about how timestamps are generated.
> fix(db): do not set createdAt, verifierSetAt or normalizedEmail here

- grunttasks/bump.js
- grunttasks/copyright.js
- grunttasks/jshint.js
- grunttasks/version.js
- npm-shrinkwrap.json
- package.json
Same as fxa-auth-server; similar to fxa-content-server but doesn't write the CHANGELOG for you from 'fix(foo): yoop' comments. @chilts @pdehaan r?
> fix(release): add tasks "grunt version" and "grunt version:patch" to create release tags

- npm-shrinkwrap.json
- package.json
Since node-uuid / uuid has been removed from fxa-auth-db-server, we no
longer have to install it here. Having it here used to upset shrinkwrap
if conflicting versions were being used and/or installed (e.g. uuid v1 to
uuid v2 - the APIs were incompatible).
> fix(package): Remove uuid completely since no longer needed

- db/schema/patch-008-007.sql
- db/schema/patch-009-008.sql
When upgrading to a new mysql-patcher and testing old patches, these were
failing on the reverse patches. Fixed both a syntax error and a non-existant
stored procedure.
> fix(db): Fix reverse patches 8->7 and 9->8

- npm-shrinkwrap.json
- package.json
To be able to add other files to the db/schema/ directory we need to update
to mysql-patcher@0.7.0 so that it will ignore non-sql patch files. It also
has a few minor updates too.
> chore(package): Update to mysql-patcher@0.7.0

- db/mysql.js
- db/patch.js
- db/schema/README.md
- db/schema/patch-009-010.sql
- db/schema/patch-010-009.sql
Every now and again, we get a deadlock in the database. Whilst these are
expected from time to time we may be able to mitigate it further by making
sure we access our tables in a consistent order. This may not always be
possible but we can do it with these three stored procedures.
Fixes #28
> refactor(db): Change table access in stored procedures to be consistent

- npm-shrinkwrap.json
- package.json
When doing an `npm install` using node v0.12, it complains since grunt-copyright
v0.1 has a `"node": "0.10.x"` in it's `engines` section. v0.2 has been updated
to be `"node": ">= 0.10.0"` which is satisfied with either v0.10 or v0.12.
> chore(copyright): Update to grunt-copyright v0.2.0

- npm-shrinkwrap.json
Fixes https://github.com/mozilla/fxa-content-server/issues/2511, part of https://github.com/mozilla/fxa-auth-server/pull/943
> fix(npm): Update npm-shrinkwrap to include the last version of fxa-auth-db-server

- lib/db/mysql.js
- test/local/event_log.js
r? anyone. Is this the best way to do this. Not needed for production, but would be nice to remove this spew in fxa-dev log asap.
> fix(notifications): always return a promise from db.processUnpublishedEvents, fixes #49

- lib/db/patch.js
- lib/db/schema/patch-011-012.sql
- lib/db/schema/patch-012-011.sql
Even though these old stored procedures don't really take up much space
in the database, they could be mis-used if left around.
Fixes #22
> refactor(db): Remove old stored procedures that are no longer used

- npm-shrinkwrap.json
- test/backend/remote.js
This updates `test/backend/remote.js` to match the change in https://github.com/mozilla/fxa-auth-db-mem/commit/122bc686b9b45f9a9886f19a23b880d9a0291232
It also updates shrinkwrap to pick up current HEAD of fxa-auth-db-server, which revealed this broken test. Uugghhh. 
Clearly we need to fold these repos together - https://github.com/mozilla/fxa-auth-db-mysql/pull/56
May I propose that no further changes to fxa-auth-db* be made, until that change can happen (modulo, of course, any changes that absolutely cannot be deferred).
> fix(tests): pass server object to backend tests (and update shrinkwrap to latest)

- .gitignore
I'm surprised this hasn't annoyed anyone else enough to have been done already.
Anyway, the readme tells me to create `config/dev.js` but it isn't in the ignore file, so I'm constantly afeared of accidentally committing it to the repo.
> chore(git): Add config/dev.js to .gitignore

- package.json
- test/mem/db_tests.js
- test/mem/remote.js
Fixes #66.
@dannycoates or @jrgm, any chance of an r?
I know there is duplication of boilerplate test code here but I was hoping we could refactor that out down the line. In the meantime, this gets us working and allows me to point `db-server` at this repo instead of `db-mem`.
> chore(package): expose scripts for running and testing db-mem

- fxa-auth-db-server/docs/DB_API.md
- fxa-auth-db-server/docs/Server_API.md
- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- fxa-auth-db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-014-015.sql
- lib/db/schema/patch-015-014.sql
Partially addresses https://github.com/mozilla/fxa-auth-server/issues/983.
Related to https://github.com/mozilla/fxa-auth-server/pull/997.
Contains the following changes:
* Adds `userAgent`, `os`, `deviceType` and `lastAccessTime` fields to the `sessionTokens` entity.
* Adds `updateSessionToken` stored procedure.
* Updates the `createSessionToken` and `sessionToken` stored procedures.
~~Some things I was unsure about, so probably need changing:~~
* ~~How to handle truncation of long UA strings? In the stored procedure or in the JS function or in `fxa-auth-db-server`? I'm not doing it anywhere yet.~~
* ~~I haven't retired the old stored procedures yet. Is that right or wrong?~~
> feat(db): store user agent and last-access time in sessionTokens

- bin/mem.js
- bin/server.js
- index.js
- npm-shrinkwrap.json
- package.json
- test/backend/db_tests.js
- test/backend/remote.js
- test/local/event_log.js
- test/local/incorrect-patch-level.js
- test/local/log-stats.js
- test/local/mysql_tests.js
- test/local/prune_tokens.js
- test/mem/db_tests.js
- test/mem/remote.js
The npm 'file' trick doesn't work when this package is required by another, i.e. fxa-auth-server. Instead, directly require files in the fxa-auth-db-server dir and duplicate the restify dep.
@philbooth @jrgm
> reshuffle package.json

- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/db_tests.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-015-016.sql
- lib/db/schema/patch-016-015.sql
This adds an endpoint for getting account info with an OpenID identifier and updates account create/delete for an optional OpenID.
A new table `openids` stores the relation between OpenID identifier and uid. Since these identifiers can be fairly long I added a sha256 hash as the primary key. I'm not 100% sure whether that's a good idea or not.
> Preliminary support for authenticating with OpenID

- bin/metrics.js
- lib/db/mysql.js
- package.json
- test/local/metrics_tests.js
- test/local/mysql_tests.js
Fixes #72.
This is essentially a like-for-like replacement for [`puppet-config/.../gather_basic_metrics.py`](https://github.com/mozilla-services/puppet-config/blob/master/fxa/modules/fxa_admin/files/gather_basic_metrics.py), except written for node.js and covered by tests.
Although it is part of this repo, the plan is for it to run from the same context as the Python script, hence the file paths and the [non-JSON config format](https://github.com/mozilla-services/puppet-config/blob/master/fxa/modules/fxa_admin/templates/gather_basic_metrics.conf.erb). By having it in this repo, we get the benefit of the tests running automatically against future schema changes.
I plan to commit some more tests tomorrow, but wanted to get feedback on it sooner than that because we're so close to the end of …
> feat(db): add script for reporting metrics

- scripts/tap-coverage.js
The coverage report was impossible to read because of a bunch of long `node_modules` paths that were no longer being excluded after the repo merge.
> chore(coverage): exclude fxa-auth-db-server/node_modules from coverage checks

- lib/db/mem.js
This change goes towards fixing the remaining test failures reported in https://github.com/mozilla/fxa-auth-server/issues/1028.
It makes the memory backend return null for unset user-agent fields, which harmonises with the MySQL backend behaviour.
After this has been merged, https://github.com/mozilla/fxa-auth-server/pull/1030 can be merged and will fix the other failing tests, which are caused by this `null`/`undefined` discrepancy.
> fix(db): default user-agent fields to null in memory backend

- fxa-auth-db-server/index.js
- fxa-auth-db-server/lib/bufferize.js
- fxa-auth-db-server/test/local/bufferize.js
This fixes one of the failing tests reported in https://github.com/mozilla/fxa-auth-server/issues/1028, by ensuring values which come out of the auth-server UA parser are never inappropriately treated as hex-encoded data.
It's pretty ugly, but it mirrors a [similar fix](https://github.com/mozilla/fxa-auth-server/blob/master/lib/crypto/butil.js#L52) that we applied elsewhere.
I've also added a bunch of tests for the rest of the `bufferize` module, as there weren't any before.
> fix(server): prevent insane bufferization of non-hex parameters

- scripts/metrics-loop.sh
- scripts/metrics-perf.sh
These are a couple of shell scripts I'm using to measure the performance impact of the metrics queries. They don't do a great deal themselves, they just stand on the shoulders of [`fxa-auth-server/test/load`](https://github.com/mozilla/fxa-auth-server/tree/master/test/load) and [`bin/metrics.js`](https://github.com/mozilla/fxa-auth-db-mysql/blob/master/bin/metrics.js).
I figured it was worth committing them to this repo so that we can easily re-use them as more metrics queries get added in the future.
@jrgm or @rfk r?
> chore(metrics): add scripts for perf-testing metrics queries

- scripts/metrics-perf.sh
My previous attempt at this script was just an epic fail, sorry. I should not have merged it into `master`.
The main problem fixed in this PR is my desperately foolish attempt to use the duration of a fixed-period load test as a benchmark/comparison. Now it reports the number of requests and the average requests per second instead.
Another problem it fixes is a variable name that I mystifyingly changed in one place but not the other. That condition isn't entered when the load tests are run on a separate machine to the metrics queries, so I didn't spot it when I was running in EC2.
The final change is to fix the path name to the script in the comments.
> fix(metrics): measure request count and time in perf tests

- scripts/populate-session-tokens.js
Not sure whether or not this is worth adding to the repo but, just in case we want it again in the future, this is the script I used to create session tokens in my local database for the perf tests. Running four of these in parallel on my machine, it created 10 million new accounts with various numbers of linked session tokens in about 2 hours or so.
The ratios for number-of-session-tokens-per-account are completely arbitrary, they can probably be tweaked for realism (currently 1/6th of the new accounts are given 3 sessions, 1/6th are given 2 sessions and 2/3rds are given 1 session).
@rfk r?
> chore(metrics): add script for creating dummy session tokens

- docs/API.md
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-017-018.sql
- lib/db/schema/patch-018-017.sql
This change enables https://github.com/mozilla/fxa-auth-server/pull/1056 to work without making an extra query against the `accounts` table to get the value of `createdAt`.
There is already a migration ([016-017](https://github.com/mozilla/fxa-auth-db-mysql/pull/102)) in this train, but I figured it was probably too late in the day to mess about adding to it here. So I've added an 017-018 migration too, but let me know if you'd rather fold this into that first one.
> feat(db): return accountCreatedAt from sessionToken stored procedure

- .travis.yml
- config/config.js
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/index.js
- fxa-auth-db-server/package.json
- fxa-auth-db-server/test/backend/db_tests.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-018-019.sql
- lib/db/schema/patch-019-018.sql
- npm-shrinkwrap.json
- package.json
- test/local/notifier.js
new endpoints for the device api
(stealth edit by @rfk to link things in waffle: Fixes #104)
> device api endpoints

- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- fxa-auth-db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-019-020.sql
- lib/db/schema/patch-020-019.sql
There are ~~two~~ three changes here:
1. Fixes #114, adding a column for the push callback public key.
2. [Return an error if a device attempts to register a session token that is already registered to another device](https://github.com/mozilla/fxa/tree/master/features/FxA-45-device-registration-api#registered-device-1).
3. [Return an error from the `POST` and `DELETE` endpoints if an unrecognised device id is received](https://github.com/mozilla/fxa/issues/78).
I put them ~~both~~ all into the same commit because I wanted to limit database changes to a single migration and I figured one migration should always be one atomic commit.
~~My approach to `2`, especially, may be (is probably?) wrong. It performs two extra queries in the worst case and then aborts the stored procedure using …
> feat(db): update devices to match new requirements

- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/remote.js
'/' and '/__version__' will how show the constructor class name, like so:
```
{"version":"0.48.0","implementation":"MySql"}
```
Not sure how I'm going to use it yet, but seems like a useful thing to be able to query.
> fix(version): print out constructor class name; adds /__version__ alias

- fxa-auth-db-server/test/backend/db_tests.js
- lib/db/mem.js
The memory-store backend was not initialising missing device fields to `null`. I didn't notice because there was (another) gap in my test coverage. Fixing https://github.com/mozilla/fxa-auth-server/issues/1123 in the auth server uncovered this problem.
> fix(db): fix memory-store initialisation of device fields to null

- .travis.yml
Test on 4.x, and failures no longer ok on 0.12 (or 4.x)
> fix(travis): build and test on 0.10, 0.12 and 4.x, and allow failure on >= 5.x

- docs/API.md
- fxa-auth-db-server/test/backend/db_tests.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-021-022.sql
- lib/db/schema/patch-022-021.sql
Fixes the root cause of the recent 500 errors that have been occurring on the `/devices` endpoint by ensuring that device records are expunged during account reset. They are already expunged during account delete.
The existing `resetAccount` test was already asserting there are no devices after the reset, it just needed tweaking to actually create a device first.
@jrgm, @rfk r?
> fix(db): expunge devices in resetAccount sproc

- lib/db/mysql.js
- lib/notifier.js
- test/lib/log.js
- test/local/notifier.js
It turns out that not all of the logging calls in this repo had been converted to call mozlog according to mozlog calling conventions. Mostly this was on error paths, and, for example, when I had to do db upgrades, I'd get the highly informative `server.bin.[Object object]` with no error details. 
PR is in 3 parts:
1. Since most of the tests stub out the logging, I added mozlog-like assertions. This detected a fair share of the bad call sites, but not all. (Although, I had to run the tests with `node test/local/foo.js`, since within the test harness, you'd just get hard-to-grok test failures). 
2. Fix all the bad calls to `log.foo` or `logger.foo`. Please review that I don't have any typos, since there isn't complete coverage on some of these error paths.
3. Adjust the notifier tests to …
> Really use mozlog everywhere in this module

- scripts/analyze-mx-stats.js
Here's broadly what I had in mind for https://github.com/mozilla/fxa-auth-server/issues/1237 - a script that takes a random sample of emails from the accounts table, figures out their canonical mail host, and prints some stats on the most popular ones.
Sample output from running it on stable.dev.lcip.org:
```
Of 949 email addresses:
69.1% of emails use google.com
including 26.9% requiring dynamic lookup to resolve to google.com
26.2% of emails use googlemail.com
including 26.2% requiring dynamic lookup to resolve to googlemail.com
10.3% of emails use messagingengine.com
including 0% requiring dynamic lookup to resolve to messagingengine.com
3.8% of emails use mailinator.com
including 0.5% requiring dynamic lookup to resolve to mailinator.com
3.5% of emails use yahoodns.net
including 0% …
```
> feat(mx-stats):  Add a script to print stats on popular mail providers.

- .travis.yml
- docs/API.md
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- fxa-auth-db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-022-023.sql
- lib/db/schema/patch-023-022.sql
- npm-shrinkwrap.json
- package.json
This PR:
- Stores the Public Key according to the current (probably last) browser implementation
- Adds support for the Auth Key
We store:
- The Public Key as a urlsafe base 64 string (65 bytes array = string of 88 chars max)
- The Auth Key as a urlsafe base 64 string (16 bytes array = string of 24 chars max)
I would love to have some feedback on this.
Resources used for implementation:
https://www.w3.org/TR/push-api/
https://jrconlin.github.io/WebPushDataTestPage/
> feat(db): store push keys according to the current implementation

- docs/API.md
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- fxa-auth-db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-023-024.sql
- lib/db/schema/patch-024-023.sql
- test/local/metrics_tests.js
This covers all of the database changes for FxA-83, sign-in confirmation. I realise the feature document isn't actually finished yet but, as I'd already made a start on this, I wanted to get it into review so that nobody is blocked from working on other parts of the feature.
The approach taken is based on (my understanding of) @dannycoates' recommendation from the Google Doc:
* A new table is added, `unverifiedTokens`, and the create/delete stored procedures for `sessionTokens` and `keyFetchTokens` maintain it appropriately. ~~Fwiw, as things stand, the first cut of the auth server changes may not utilise the `keyFetchTokens` part of this, but a second version that does so should follow pretty rapidly.~~
* New endpoints, `GET /sessionToken/:id/verified` and `GET …
> feat(db): implement new token verification logic

- docs/API.md
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- fxa-auth-db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-024-025.sql
- lib/db/schema/patch-025-024.sql
This PR enables us to work round the problem of Fennec using the `/account/keys` auth server endpoint to check account status. It does so by reinstating the verification state for key fetch tokens, which is set by the presence of `tokenVerificationId` in the request payload to `PUT /keyFetchToken/:id`.
For this to work correctly with the sign-in confirmation stuff, the auth server must:
* Be updated to make requests to the plural `/tokens/:tokenVerificationId/verify`.
* Only create unverified key fetch tokens from `/account/signup` and `/account/login` (i.e. not on password change).
* Specify the same `tokenVerificationId` as it does for the equivalent session token.
* Reject requests to `/account/keys` that use an unverified token, with `errno` 104.
@vbudhram @rfk r?
/cc @shane-tomlinson
> feat(db): implement verification state for key fetch tokens

- npm-shrinkwrap.json
- package.json
- update mozlog@2.0.3 to 2.0.5 for a couple of error logging fixes
- sort npm scripts
- add 'npm run shrinkwrap' script
r? - @philbooth
> Update mozlog 2.0.3 2.0.5

- docs/API.md
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- fxa-auth-db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-026-027.sql
- lib/db/schema/patch-027-026.sql
- test/local/prune_tokens.js
Fixes #150. Will need to be rebased after #153 is merged.
I'm not 100% certain that we actually want to do this, although there wasn't any disagreement on the issue.
Anyway, this removes the endpoint and stored procedure for `createAccountResetToken`. They're never called and the corresponding auth server code was removed in https://github.com/mozilla/fxa-auth-server/pull/1384. Account reset tokens are exclusively created through the `forgotPasswordVerified` stored procedure.
Both me and @rfk had a look in Kibana for requests to this endpoint, none were found.
However, given my track record in this repo, it's quite possible that I've missed some crucial unforeseen operational effect on the production db.
@rfk, @jrgm r?
> fix(db): remove createAccountResetToken stored procedure and endpoint

- docs/API.md
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- fxa-auth-db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-028-029.sql
- lib/db/schema/patch-029-028.sql
Fixes #151.
@pb @vbudhram here's my sketch for how we might explicitly track whether an unverified sessionToken wanted keys or not.  It will require a corresponding change in the auth-server to send over the new state, which I've added in https://github.com/mozilla/fxa-auth-server/pull/1376.  In particular, see here for how I think we'd want to use it:
https://github.com/mozilla/fxa-auth-server/pull/1376/files#diff-ab87c506e682e952973178a41792df12R1158
Does this seem like a reasonable path forward?
> feat(db): Record whether unverified tokens must be verified before use.

- CHANGELOG.md
- grunttasks/bump.js
- grunttasks/changelog.js
- grunttasks/version.js
- npm-shrinkwrap.json
- package.json
Fixes #156, previously attempted at #158.
This repo didn't have the change log stuff the other repos do, so I've included it and call out to it from the version script. I've also moved the change log back to the old file name of `CHANGELOG.md` and included the missing commit details from the interim releases. The old `fxa-auth-db-server` change log is still available as `CHANGELOG-server.md`. And shrinkwrap is updated.
@vbudhram, actually tested this time, can I get an r?
> fix(scripts): ensure changelog is updated sanely

- docs/API.md
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-029-30.sql
- lib/db/schema/patch-030-029.sql
Fixes mozilla/fxa-auth-server#1423 (although I've found another related problem that we also need to fix, see mozilla/fxa-content-server#4060).
The fix itself is straightforward, just ensuring that we delete any device records inside `deleteSessionToken`. However there is also another change in the migration that may be contentious: I'm explicitly purging all session-less device records.
This is because any such records only exist in our db because of earlier problems with our implementation of device registration. I can think of no legitimate reason for them to exist and we definitely don't want them to show up in anyone's device list.
@rfk, I'm tagging you for the review because of the contentious bit, are you comfortable with us doing that? I know we discussed earlier on about only …
> fix(db): ensure that devices get deleted with session tokens

- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-030-031.sql
- lib/db/schema/patch-031-030.sql
Fixes #162.
Possibly this is wrong because I've ploughed the `INNER JOIN` furrow raised in https://github.com/mozilla/fxa-auth-db-mysql/issues/162#issuecomment-243435229, without waiting for feedback. I figured I may as well offer something concrete to discuss.
(and sorry about #164, ignore everything I said there!)
> fix(db): don't return zombie devices from accountDevices

- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/README.md
- lib/db/schema/patch-031-032.sql
- lib/db/schema/patch-032-031.sql
@jrgm thinks that the `lockedAt` column on the account table does not take
up enough space to warrant the effort needed to remove it.
@philbooth - mind having an initial look at this to see if I'm in the right track?
> refactor(db): Remove account unlock related code.

- bin/server.js
- lib/newrelic.js
- npm-shrinkwrap.json
- package.json
Aaannnd.... fxa-auth-db-mysql
svcops would like to make use of New Relic. This PR just makes it possible to load the module if explicitly configured. Further configuration will happen with puppet in the circusd environment (unless we have to set so many switches that a sane configuration file makes sense).
r? @rfk
> Add optional newrelic

- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-033-034.sql
- lib/db/schema/patch-034-033.sql
This enables us to sample users by email address for the feature flag I'm adding for `device.lastAccessTime` in the auth server (see https://github.com/mozilla/fxa-auth-server/issues/1460).
@vladikoff or @vbudhram, r?
> feat(db): return account.email from accountDevices

- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/db_tests.js
- lib/db/mem.js
- lib/db/mysql.js
There were problems with the auth-server integration.
* convert GET /securityEvents to GET /securityEvents/:id/ip/:ipAddr
to be more RESTful and work with the auth-server's pool get API
* for POST /securityEvents, pass the body and query parameters, fixing the
former attempt to pass the param's id and body.
* in fxa-auth-db-server/index.js, add 3 helper functions so it's easy to know
what data is passed to the db methods.
fixes #171 
@rfk, @seanmonstar - r?
> fix(security): Fix the endpoints for /securityEvents.

- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-035-036.sql
- lib/db/schema/patch-036-035.sql
Here's some proposed tweaks to the DB queries for security events, based on feedback/concerns from @jrgm in https://bugzilla.mozilla.org/show_bug.cgi?id=1304287#c8
* Add `createdAt` to the index we use for fetching the events
* Store the tokenVerificationId on the event, so that we can directly look it up to verify it rather than indirecting through the tokenId.
The fetch query no longer threatens to use a filesort:
```
mysql> explain     SELECT         n.name,         e.verified,         e.createdAt     FROM         securityEvents e     LEFT JOIN securityEventNames n         ON e.nameId = n.id     WHERE         e.uid = unhex('000000111')     AND         e.ipAddr
+----+-------------+-------+------------+--------+------------------------------------------------------------------------------ …
```
> fix(securityEvents): Tweak securityEvents db queries based on @jrgm feedback

- fxa-auth-db-server/index.js
- fxa-auth-db-server/lib/bufferize.js
- fxa-auth-db-server/test/backend/remote.js
- fxa-auth-db-server/test/local/bufferize.js
The previous behaviour was to automagically bufferize anything that looked like a hex string, unless it was on an explicit list of "things we don't want as buffers".  A list we've failed to keep up to date.
This changes it to use an explicit list of things that we expect to be buffers, and leave everything else alone.  It removes the guesswork and the associated potential for unexpected foot/bullet
interactions.
To nobody's surprise, this was masking a couple of (thankfully harmless) bugs in our test suite.
@philbooth r?
> fix(bufferize): Only bufferize params we explicitly want as buffers.

- docs/API.md
- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-040-041.sql
- lib/db/schema/patch-041-040.sql
- lib/db/util.js
I have some code to also add `fetchEmailBounces(email)`, but was left with an implementation detail I wanted to talk out.
This is currently changed `bounceType` and `bounceSubType` into integers, since it is more efficient to store ints than varchars, and also more efficient to query on them if want to make specific queries.
This means that returning the rows, the raw values are different than what is stored in the `memory` version. Does it seem nice to just universally store them as integral "type" codes, or should they be mapped to a string version coming out of the DB? I feel like having them be integers makes it harder to typo names if we start filtering on types down the road, and so I'm leaning towards having the same mapping in the `memory` db... I'll mull on it over night, and …
> feat(db): add emailBounces table

- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-043-044.sql
- lib/db/schema/patch-044-043.sql
- test/local/mysql_tests.js
The PR updates the `emailRecord` mysql db call to return its `createdAt` value as well. This matches what the mem db call returns.
Connects with https://github.com/mozilla/fxa-auth-server/issues/1671
@rfk r?
> fix(email): Return `createdAt` when calling mysql db.emailRecord

- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/remote.js
- lib/db/mysql.js
The auth server hasn't used this route yet, so no coordination dance required. This makes it match `/emailRecord/:id`.
> fix(emailBounces): receive the email parameter in the url as hex

- fxa-auth-db-server/test/backend/db_tests.js
- lib/db/mem.js
The 'account.reset' security event may not be associated with a session token, but we didn't have sufficient test coverage for this.  The mem and mysql backends were handling it differently, and the mem backout would error out in some cases.  This PR:
* Fixes a bug in the mem backend where it might try to dereference an undefined tokenId
* Adds a test that events without a token are *verified* by default, and changes the mem backend to match this behaviour, which was already present in the mysql backend.
* Makes the mem backend return results most-recent-first, matching how the mysql backend does it.
@seanmonstar does this sound correct?
> fix(security-events): Correctly handle tokenless security events in mem backend

- docs/API.md
- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-046-047.sql
- lib/db/schema/patch-047-046.sql
This PR adds the `getEmail` endpoint. It will be used only by the auth-server to get a single email on the secondary table, which will then let the it intelligently choose how to proceed on login (display correct error message) or account create (display email unavailable).
Fixes #226 
> feat(email): Add get email endpoint

- fxa-auth-db-server/test/backend/db_tests.js
- lib/db/mysql.js
This PR fixes the issue where secondary emails were not being deleted from the emails table when the account was delete. This caused new account creation to fail if they attempted to use an email in the secondary table. The procedure was [created](https://github.com/mozilla/fxa-auth-db-mysql/blob/master/lib/db/schema/patch-045-046.sql#L152) but the call in mysql was not updated it use it >.<
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1362589.
> fix(email): Use correct delete account procedure

- docs/API.md
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-047-048.sql
- lib/db/schema/patch-048-047.sql
Fixes #230. Replaces #234, implementing some of the suggested feedback from that PR.
Unresolved questions from that PR, copied over so we can continue the discussion here.
* https://github.com/mozilla/fxa-auth-db-mysql/pull/234#discussion_r115950898
> @philbooth: I'm deeply uncertain about the name of this endpoint, if anyone has better suggestions hit me!
> @vbudhram: Going to go out a limb and suggest `/code/signin/:code`. This might give us a little flexibility later on if we get different types of codes, ex 2FA.
> @philbooth: I quite like `signinCodes` in the path because it matches the name of the underlying table and shows up when grepping for it.
* https://github.com/mozilla/fxa-auth-db-mysql/pull/234#discussion_r116005508
> @vbudhram: The use of `DELETE` here seems a little …
> feat(signinCodes): migration and endpoints for signinCodes table

- config/config.js
- docs/API.md
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-048-049.sql
- lib/db/schema/patch-049-048.sql
- test/local/prune_tokens.js
Fixes mozilla/fxa-auth-server#1898.
I opened that issue in the auth server because I thought I'd stick the responsibility for it in an auth server process and call the existing endpoint for expiring sign-in codes. @rfk subsequently pointed out that we already have logic for expiring stuff in this repo so I should lean on that, which is what I've done here.
One side-effect of leaning on that code is that `signinCodes` will hang around in the table for 3 months before they're physically deleted. There's no harm in that of course, and it could even be useful if we ever decide to lengthen the expiry period. But 3 months does seem a bit unnecessary so if people want, I could tweak the logic so that `signinCodes` gets a different max-age to the token tables.
Other than that this should …
> feat(db): enable signinCode expiry

- lib/db/patch.js
- lib/db/schema/patch-050-051.sql
- lib/db/schema/patch-051-050.sql
New and improved email table migration script. Copies all emails on the account table into the emails table.
Replaces https://github.com/mozilla/fxa-auth-db-mysql/pull/243. This will be a point release for the next train.
> feat(email): Add email table migration script

- docs/API.md
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/index.js
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-052-053.sql
- lib/db/schema/patch-053-052.sql
Related to mozilla/fxa-auth-server#1945.
Stores `flowId` in the `signinCodes` table so that we can emit a `flow.continued` event in the auth server, which enables us to link up the flows at either end of connect another device.
(and @vbudhram, sorry for yet another merge conflict in this repo, maybe you will merge ahead of me this time :smile:)
> feat(db): store flowIds with signinCodes

- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-051-052.sql
- lib/db/schema/patch-052-051.sql
The PR removes the use of a temporary table in favor of using a select statement. This is the exact query that was planned for next [train](https://github.com/mozilla/fxa-auth-db-mysql/blob/c5a4ad50d412dc0dd4e3e53a24aeda3ee85b9fde/lib/db/schema/patch-051-052.sql#L1).
Using this query assumes that all email data has been migrated to the emails table. I believe we would still have to merge this back into master, to ensure it correctly matches state of database.
@jbuck @rfk r?
> feat(email): Remove temporary table from `accountEmails` query

- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-052-053.sql
- lib/db/schema/patch-053-052.sql
From deployment, noticed that the `forgotPasswordVerify` SP was taking extra long to run. Turns out that the updated procedure was performing a table scan
`UPDATE emails SET isVerified = true WHERE email = (SELECT email FROM accounts WHERE uid = inUid); `
This PR updates SP to use index `normalizedEmail` on the WHERE clause and SELECT `normalizedEmail` from account table.
SQL Explain
Not sure if this will 100% remove all timeouts, but should increase speed of query.
@jbuck @jrgm Thoughts? r?
> feat(email): Use an index when performing update in forgotPasswordVerify

- fxa-auth-db-server/test/backend/db_tests.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-057-058.sql
- lib/db/schema/patch-058-057.sql
Slight oversight in the mysql implementation for `accountRecord`, it didn't not return `createdBy` which caused https://travis-ci.org/mozilla/fxa-auth-server/jobs/252105845 to fail. Unfortunately, I did not catch this early enough and I'm guessing the migration has already run?
The tests now correctly pass on auth-server, https://travis-ci.org/mozilla/fxa-auth-server/builds/252500226.
@philbooth Sorry about that 😢, mind an r?
> feat(email): correctly return `createdAt` when using accountRecord

- docs/API.md
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- fxa-auth-db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-058-059.sql
- lib/db/schema/patch-059-058.sql
Fixes #239, adding a `uaFormFactor` column to `sessionTokens`. This is so that we can include information like `iPhone 6S` in the devices view, once all the pieces are in place. Overloading the `uaDeviceType` column with this information is not possible because we already have logic hanging off the `mobile` / `tablet` distinction that we make there.
I didn't bother updating the stored procedure for `updateSessionToken` because we don't use it and are hopefully going to delete it for #255. But the stored procedures for creating and reading session tokens are changed accordingly.
> feat(schema): add a uaFormFactor column to sessionTokens

- Dockerfile-build
This needs to be in a 1.91.1 tag.
> fix(nodejs): upgrade to 4.8.4 for security fixes

- package.json
Fixes #257.
I should be able to run the tests locally without eslint getting in my grill about `console.log` or whatever. This does that.
> chore(tests): don't make eslint a prerequisite for the tests

- scripts/migration.sh
Fixes #202.
I noticed this issue for the first time yesterday, hadn't spotted it before. A script that generates migration boilerplate seems like a handy addition, so here is my first stab at one. It creates forward and reverse migration scripts and updates `lib/db/patch.js`.
> chore(scripts): add a script to generate migration boilerplate

- docs/API.md
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- fxa-auth-db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-059-060.sql
- lib/db/schema/patch-060-059.sql
As per discussion in the deployment bug, we have too many records in the `sessionTokens` table to add a new column in prod. This PR reverts train-91 to the previous state, but done as a forward migration with incremented stored procedures for the benefit of the patcher script.
An auth server patch will also be required, I'll write that one in a jiffy.
@vbudhram r?
> feat(schema): drop the uaFormFactor column from sessionTokens

- docs/API.md
- lib/db/mem.js
- lib/db/mysql.js
Fixes https://github.com/mozilla/fxa-auth-server/issues/1999.
Unfortunately, I don't have any solid plans to get this method depreciated and it might not be possible to do without breaking backwards compatibility on user's accounts. This PR drops the deprecation warnings.
> chore(email): Remove emailRecord depreciation

- docs/API.md
- fxa-auth-db-server/docs/API.md
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- fxa-auth-db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-062-063.sql
- lib/db/schema/patch-063-062.sql
This connects to https://github.com/mozilla/fxa-auth-server/issues/1873.
The `createDevices` procedure is not modified, `pushEndpointExpired` is set by default to `FALSE`.
> feat(schema): add a pushEndpointExpired column to devices

- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-063-064.sql
- lib/db/schema/patch-064-063.sql
- test/local/prune_tokens.js
Fixes #263. Supercedes #274.
Please let me know if there is a better way to do this.
Initially I tried to do it all in one query, with a `LEFT JOIN` between `sessionTokens` and `devices` and an `INNER JOIN` between `sessionTokens` and `unverifiedTokens`. But that doesn't work because, [as per the docs](https://dev.mysql.com/doc/refman/5.7/en/delete.html#idm140189111263328):
> You cannot use `ORDER BY` or `LIMIT` in a multiple-table `DELETE`.
So instead, I've broken it down to two queries. The first uses `NOT EXISTS` and a subquery to deselect session tokens with device records, which allows us to sanely delete from `sessionTokens` with `ORDER BY` and `LIMIT`. Then the second one just mops up any zombies left behind in `unverifiedTokens`, which we don't/shouldn't need to worry about …
> fix(tokens): prune old session tokens that have no device record

- lib/db/patch.js
- lib/db/schema/patch-065-066.sql
- lib/db/schema/patch-066-065.sql
- test/local/prune_tokens.js
Fixes #278 (in a manner of speaking).
Reinstates the old behaviour from `prune_3`, so that token pruning can be enabled for train 96. See #279 for discussions of the failed attempt(s) to fix session-token pruning. The original problematic code was introduced by #275.
> fix(tokens): revert session-token pruning

- lib/db/mysql.js
- test/local/prune_tokens.js
When I reverted session token pruning, I failed to update the procedure version in `lib/db/mysql.js`. This went undetected by the tests because nothing was there to assert that session tokens *weren't* being pruned. I've added that test here to go with the fix.
> fix(db): call latest version of the prune stored procedure

- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-066-067.sql
- lib/db/schema/patch-067-066.sql
- test/local/prune_tokens.js
Fixes #263.
Earlier on, @rfk was kind enough to point out that simply including `uid` in the `devices` join would allow MySQL to use the existing index on `devices` and make session token pruning fast. I tried it just now and, of course, he was dead right.
But don't take my word for it, here are the numbers:
```
mysql> select count(*) from sessionTokens;
+----------+
| count(*) |
+----------+
|  6000016 |
+----------+
1 row in set (1.49 sec)
mysql> select count(*)
-> from sessionTokens as t
-> left join devices as d
-> on t.tokenId = d.sessionTokenId and t.uid = d.uid
-> where d.id is null;
+----------+
| count(*) |
+----------+
|  1333348 |
+----------+
1 row in set (20.92 sec)
mysql> call prune_6(1505929326193);
+------------------------------------------------------------+
| …
```
> feat(db): prune session tokens (again)

- .travis.yml
- package.json
run on 6 and 8, and removes the matrix that allowed "stable" to fail. Both must pass.
This repo was running `npm outdated`. With npm < 5, it would exit 0; with npm >= 5, it now exits 1. I just made it behave like before, but not sure what it's trying to do (just show what is outdated?).
r? - @rfk
> fix(travis): run tests with 6 and current stable (failure not allowed anymore)

- bin/server.js
- npm-shrinkwrap.json
- package.json
This PR supersedes https://github.com/mozilla/fxa-auth-db-mysql/pull/284 which just added a futureproofing comment, to update the newrelic module to latest 2.3.2, with an `npm run shrink` using npm@2.15.1
r? - @vladikoff
> futureproofing comment and up to newrelic@2.3.2 with npm run shrink

- docs/API.md
- fxa-auth-db-server/index.js
- fxa-auth-db-server/lib/error.js
- fxa-auth-db-server/test/backend/db_tests.js
- fxa-auth-db-server/test/backend/remote.js
- fxa-auth-db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-067-068.sql
- lib/db/schema/patch-068-067.sql
- lib/db/util.js
This PR exposes new APIs to create and verify sessionTokens using a short code. Couple notes
- Each code has an expiration date
- Codes are stored as hashes in database
- Support for resending (aka regenerating) a code to come in later PR.
- New endpoint `verifyTokensShortCode` used to explicitly verify shortCodes. 
Connects with https://github.com/mozilla/fxa-auth-server/pull/2218
Feature doc: https://docs.google.com/document/d/1xQtCGBJ9XZuF1q9faZV3YIiOnxomQMHKiTP62YSf3v8/edit
> feat(codes): add support for verifying token short code

- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-068-069.sql
- lib/db/schema/patch-069-068.sql
- test/local/prune_tokens.js
This adjusts the session-pruning logic to address two observations from #294.
First, it adds an explicit check for whether `@pruneUntil` is `NULL`, and short-circuits if so.  This indicates that no expired tokens are available to prune.
Second, it changes the way that `@pruneUntil` is calculated, by dropping the filter on "does this session have a decide record?".  This is to help us deal better with a database that's already been partly pruned, and hence has a session token timeline like:
```
|--- millions of device sessions ---|--- a mix of device- and non-device sessions ---|
```
The previous version would calculate `@pruneUntil` to be *after* the millions of unexpirable tokens in the early part of the timeline, forcing the subsequent `DELETE` statement to wastefully examine them all. …
> fix(pruning): Avoid accidentally full-table scans when pruning session tokens

- db-server/test/backend/db_tests.js
- db-server/test/backend/remote.js
- docs/API.md
- docs/DB_API.md
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-069-070.sql
- lib/db/schema/patch-070-069.sql
Related to mozilla/fxa-auth-server#2260.
Currently, the auth server doesn't delete session tokens from Redis in its `db.deleteDevice` method. In order to fix that, the auth server needs to know the session token id for the deleted device. I figured the easiest way to do that would be just to return it from this repo's `deleteDevice` method. Although perhaps it isn't the "correct" way in API terms, I don't know.
Anyway, here it is. If this approach does seem okay, it would be great if we could include this in train 104, so that train 105 can contain the equivalent auth server changes. No dramas if it doesn't make it though.
> feat(devices): return session token id from deleteDevice

- db-server/test/backend/db_tests.js
- lib/db/mem.js
This PR updates the db tests to use more features of mocha. This is cleanup work that will make working with this repo more manageable.
- Tests can run independently of each other
- Testing blocks are much smaller with same coverage
- Expanded some tests and removed duplicate tests
- Removed checking email on change password token https://github.com/mozilla/fxa-auth-db-mysql/pull/293/commits/9cc30b1ca88547a933d255b7b44dbc658489ffda. Turns out that mysql was not returning this but the mem db was. Looking at the auth-server the email was not being used so I think it is fair to remove from mem.
The easiest way I think this could be reviewed is doing a side by side comparison of original db tests. Sorry in advance for including some styling changes :(
Fixes #246
> feat(tests): make tests more independent

- db-server/test/backend/db_tests.js
- db-server/test/backend/remote.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-071-072.sql
- lib/db/schema/patch-072-071.sql
Connects to mozilla/fxa-auth-server#2212.
This adds supporting code for mozilla/fxa-auth-server#2288, allowing us to re-authenticate against an existing sessionToken rather than creating a new one whenever we need the user to re-enter their password.
It's currently implemented on top of #299 to avoid migration conflicts; let's aim to get that merged first and then we can re-open this PR against master. WIP for now.
> feat(sessions): Add support for reauth on an existing session.

- db-server/index.js
- db-server/lib/error.js
- db-server/test/backend/db_tests.js
- db-server/test/backend/remote.js
- db-server/test/fake.js
- docs/API.md
- docs/DB_API.md
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-072-073.sql
- lib/db/schema/patch-073-072.sql
- lib/db/util.js
This PR is the next stage for TOTP tokens. It adds the ability to verify TOTP tokens and sessions.
* Adds the `verified, enabled` property to TOTP tokens.
* Adds the `verificationMethod, verifiedAt` property to session tokens.
* Adds the `mustVerify` property to the session table. This property is in sync with the property on the unverified tokens table, ref: https://github.com/mozilla/fxa-auth-db-mysql/issues/301#issuecomment-366051763.
* Can be tested against https://github.com/mozilla/fxa-auth-server/pull/2321
Fixes #301
> feat(totp): Add initial totp session verification logic

- db-server/index.js
- db-server/test/backend/db_tests.js
- db-server/test/backend/remote.js
- db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- scripts/populate-session-tokens.js
- test/local/metrics_tests.js
Made changes to fix issue #311 Use email buffer for DEL ‘/email/:email’ route.
Also fixed Buffer function call to take care of deprecated format.
> Fixes issue #311 Use email buffer for DEL ‘/email/:email’ route

- db-server/lib/error.js
- db-server/test/backend/db_tests.js
- db-server/test/backend/remote.js
- db-server/test/fake.js
- docs/API.md
- docs/DB_API.md
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-073-074.sql
- lib/db/schema/patch-074-073.sql
- lib/db/util.js
Connects to mozilla/fxa-auth-server#2320 (please read for context).
- When fetching a device infos, we want to query `devices` and `devicesCapabilities` at the same time.
Since MySQL doesn't have an Array type, we pull the device capabilities using a `GROUP_CONCAT` and convert them to an array in JS.
- For creating or updating a device, we have no choice but to make multiple queries in the same transaction (see the new `writeMultiple` method).
- We maintain a "capability name" <> "capability id" mapping. In practice this is the `CAPABILITIES` array in `mysql.js`.
- If `device.capabilities` is supplied in `updateDevice`, it is implied that we are replacing the current device capabilities.
> feat(devices): Devices capabilities

- db-server/index.js
- db-server/test/backend/db_tests.js
- db-server/test/backend/remote.js
- docs/API.md
- docs/DB_API.md
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-074-075.sql
- lib/db/schema/patch-075-074.sql
- lib/db/util.js
> feat(totp): initial recovery codes

- db-server/test/backend/remote.js
Fixed and tested all problematic promised error handling calls. One modified non-existing api call was getting caught at incorrect place due to the issue. Fixed the api call at two places.
> fix(test): #321 Correct promises error handling

- db-server/test/backend/db_tests.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-075-076.sql
- lib/db/schema/patch-076-075.sql
From debugging https://github.com/mozilla/fxa-auth-server/issues/2351, I found that the `verifyTokenWithMethod` stored procedure was not correctly updating an already verified session's verificationMethod. This could help explain why https://github.com/mozilla/fxa-auth-server/pull/2346#discussion_r175366433 happened.
Either way, this PR fixes the issue and matches how the mem db's method works.
> fix(verify): `verifyTokenWithMethod` should update already verified session status

- lib/db/mysql.js
- test/local/mysql_tests.js
Fixes https://github.com/mozilla/fxa-auth-db-mysql/issues/277
- Added the query to set the sql_mode
- Added unit test to disallow any other sql_mode
> feat(mysql): #277 STRICT_ALL_TABLES required sql mode support

- db-server/test/backend/db_tests.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-076-077.sql
- lib/db/schema/patch-077-076.sql
> fix(codes): drop all codes when one is consumed

- db-server/test/backend/db_tests.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-077-078.sql
- lib/db/schema/patch-078-077.sql
This was previously deleting all unblock codes whenever it called the `consumeUnblockCode` procedure, regardless if it consumed the code or not.
@vladikoff r?
> fix(unblock): delete unblock codes only when successfully consumed code

- config/config.js
- lib/db/mysql.js
- test/local/mysql_tests.js
This also tweaks the implementation to preserve any existing mode flags on the connection, rather than overwriting them with just the modes from the required list.  That's in line with how profile-server and oauth-server approach it.
@vladikoff r?
> feat(mysql): Add config option for REQUIRED_SQL_MODES.

- db-server/test/backend/db_tests.js
- db-server/test/backend/remote.js
- db-server/test/fake.js
- docs/API.md
- lib/db/util.js
This is safe as we have no existing clients using capabilities yet and capabilities are stored as integers.
> fix(devices): Rename pushbox capability to messages

- config/config.js
- db-server/test/backend/db_tests.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-078-079.sql
- lib/db/schema/patch-079-078.sql
- lib/db/util.js
- npm-shrinkwrap.json
- package.json
- test/lib/utils.js
I was going through and reviewing requirements for recovery codes and found that there are some differences in implementation
* Should be 10 characters vs current 8
* Should be alphanumeric vs hex
* Should use scrypt/bcrypt vs sha
Ref https://docs.google.com/document/d/1m4D_7DZAfXt4e-bEbfI-5s_x2XFO7TEQo1a_SQcj1O8/edit#heading=h.yzz637baqr7a
> fix(codes): update to latest recovery codes requirements

- lib/db/schema/patch-078-079.sql
Fixes https://github.com/mozilla/fxa-auth-db-mysql/issues/336
> fix(codes): remove current recovery codes before applying migration 79

- db-server/test/backend/db_tests.js
- db-server/test/backend/remote.js
This PR increases timeout for recovery code related tests and fixes https://github.com/mozilla/fxa-auth-db-mysql/issues/338. Doing recovery code comparisons (with scrypt) was taking longer than the default 2 second timeout for tests.
```
recovery codes
✓ should generate new recovery codes (1469ms)
✓ should fail to consume unknown recovery code
✓ should consume recovery code (3193ms)
```
> fix(tests): increase timeout on recovery code tests

- db-server/index.js
The new restify uses `find-my-way` router module which defaults to max param size of [100](https://github.com/delvedor/find-my-way/blob/15b6e94667fae12a35f6eccc5f0670428dec4a20/index.js#L35). When using email routes, they could be over 100 characters after being hexed and potentially produce a 404.
Connects to https://github.com/mozilla/fxa-auth-server/issues/2433
> fix(restify): set a sane max param length value for restify

- db-server/index.js
- db-server/lib/error.js
- db-server/test/backend/db_tests.js
- db-server/test/backend/remote.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-081-082.sql
- lib/db/schema/patch-082-081.sql
- lib/db/util.js
- test/lib/utils.js
- test/local/metrics_tests.js
This is a revision of the "device capabilities" feature, to allow devices to associate a metadata blob with each advertised capability.  I've taken the liberty of renaming them from "capabilities" to "commands" for reasons that will become clear in a forthcoming auth-server PR.
WIP for now. /cc @eoger 
Connects to https://github.com/mozilla/fxa-auth-server/issues/2318
> Let devices register "available commands" with associated metadata.

- db-server/index.js
- db-server/lib/error.js
- db-server/test/backend/db_tests.js
- db-server/test/backend/remote.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-081-082.sql
- lib/db/schema/patch-082-081.sql
- lib/db/util.js
- test/lib/utils.js
- test/local/metrics_tests.js
A device's set of availalbe commands is a simple name:value mapping
that can be used by other devices to discover and invoke commands.
We make no particular commitment toward to format of the names or
values.
Re-applying this to master after backing it out in train-113.
> feat(devices): Allow devices to register "available commands". (#354); r=philbooth,eoger

- lib/db/patch.js
- lib/db/schema/patch-082-083.sql
- lib/db/schema/patch-083-082.sql
- scripts/migration.sh
- test/local/mysql_tests.js
Fixes #328.
While I was pootling around in this repo just now I realised we never got this implemented, so here's my stab at it. It just checks the current patch level matches what it should be before proceeding with the rest of the migration.
~~I had to wrap that check in a temporary stored procedure because MySQL complains if I try to do `IF` outside of one. The preceding `DROP` is so that we clean up in the presence of repeated failures. I've named the procedure specifically to the current patch level to make it hopefully more self-documenting.~~
If you want to test it out, create a fresh migration using the script and then manually change the patch level to a different value. When you run `node bin/db_patcher` it should fail like so:
```
~/c/fxa-auth-db-mysql …
```
> feat(scripts): add boilerplate to detect missing migrations

- db-server/index.js
- db-server/test/backend/db_tests.js
- db-server/test/backend/remote.js
- docs/API.md
- docs/DB_API.md
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-083-084.sql
- lib/db/schema/patch-084-083.sql
While building out https://github.com/mozilla/fxa-content-server/pull/6203, it has become more apparent that we don't need to pass the `recoveryKeyId` to get/delete a user's recovery data. `recoveryKeyId` can only be generated from the recovery key, which would cause us to prompt for it in order to get/delete the recovery data.
Additionally, user's can currently only have one recovery key so. In the future, we could re-look at removing the unique contraint.
This PR will cause some breakage in auth-server. WIP until auth-server PR is ready.
> feat(recovery): update account recovery GET/DEL to not accept recoveryKeyId

- test/local/utils.js
Fixes #376.
The tests in `test/lib/utils.js` weren't being exercised by `npm t`. Moving them into `test/local` fixes that.
Because they weren't being exercised, one of the tests had got into a failing state. Looking at it, I think it's a redundant test now because there is no keyspace argument to `generateRecoveryCodes`. Hence it's deleted here.
> fix(tests): move local utils tests so they get run by npm t

- db-server/index.js
(Same as fxa-customs-server):
Hey @vladikoff. I biffed setting this on my first try. This is the correct object location, and I've verified by watching tcpdump/netstat in stage with this fix that connections are held open until idle for 2 minutes.
> fix(restify): set keepAliveTimeout correctly on api.server object

- db-server/test/backend/db_tests.js
- lib/db/mysql.js
Temporary hack to stop writing to the `deviceCommands` table. Since we're tagging a release I figured it made sense to leave the stored procedure in place and make `makeStatementsToAddAvailableCommands` a nop in the js code instead. And of course, a bunch of tests needed to change too.
@jbuck @jrgm @eoger r?
> chore(db): stop calling the upsertAvailableCommands procedure

- lib/db/mem.js
In #383, we temporarily disabled insertion of device commands into the MySQL db. We didn't do the same with the memory db though, which means the auth server tests see different behaviour depending on which backend they're running against. This change forces the memory backend to behave the same way.
> chore(db): ensure mem db behaves like mysql db

- scripts/analyze-mx-stats.js
Spotted this in the [lgtm alerts](https://lgtm.com/projects/g/mozilla/fxa-auth-db-mysql/alerts), presumably these `!== -1` tests are left over from an old `indexOf` test. Let's get rid of them.
> fix(scripts): remove nonsense (but harmless) comparison of bool to -1

- db-server/test/backend/db_tests.js
- docs/DB_API.md
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-086-087.sql
- lib/db/schema/patch-087-086.sql
Connects to https://github.com/mozilla/fxa-auth-server/issues/2490
Fixes https://github.com/mozilla/fxa-auth-db-mysql/issues/397
This PR adds the `profileChangedAt` property to the accounts table. The property currently updated when a successful call to these methods are made
* setPrimaryEmail
* verifyEmail
* deleteEmail
* deleteTotpToken
* updateTotpToken
* deletePasswordChangeToken (password changed)
* resetAccount
I opted not to update the value when changes were made to recovery keys since that didn't feel like a core profile change (can be convinced otherwise).
The property is returned when using these methods
* sessionToken
* account
* accountRecord
> feat(account): add `profileChangedAt` property to account table

- db-server/test/backend/db_tests.js
- lib/db/mem.js
The memory backend was appending to the bounce/complaint array, which meant it was returning items in the opposite order to the MySQL backend. The order of those items is significant to our bounce and complaint handling logic.
> fix(mem): ensure emailBounces are stored most-recent first

- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-086-087.sql
- lib/db/schema/patch-087-086.sql
This PR updates our stored procedures to be more replication friendly and is targeted against train-121.
> fix(account): update stored procedures to be more replication friendly

- db-server/test/backend/db_tests.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-090-091.sql
- lib/db/schema/patch-091-090.sql
From meeting earlier this PR rollbacks the `profileChangedAt` migration on the accounts table. Below are some notes I found while creating this
* Opted to create new stored procedures instead of dropping procedures in migration 87. There was only once instance where a `DROP PROCEDURE` was performed in a forward migration and that was very early on.
* Opted to colasce `profileChangedAt` when it is return from the `veriferSetAt` and `createdAt` timestamps since it seemed to reduce code churn in auth-server. I'm not opposed to dropping this value entirely since it doesn't 100% reflect last updated time.
* I haven't fully tested with auth-server, but remote tests seem to work (minus profileChangedAt asserts).
@rfk @jrgm Thoughts on this approach?
> Train 123 rollback profilechangedat

- scripts/explain-warn.js
The explain script was using `cut` to split paths from git grep before the colon character. This fails on systems where control characters such as colours are emitted before the colon.
A more robust approach is to use a regex to pull out the specific text we're looking for. The script is already hard-coded with other paths like `lib/db/mysql.js`, so matching against the expected migration path doesn't seem like too much of a stretch to me.
@mozilla/fxa-devs r? (but mostly @shane-tomlinson r? because he has the system where we know it fails)
> fix(scripts): stop the explain script tripping over git grep colours

- lib/db/schema/patch-035-036.sql
- lib/db/schema/patch-038-039.sql
Fixes #393.
Sometimes we get self-hosters or contributors showing up who want to use MariaDB. Even though the official line is that we don't support it, it happens often enough that we may as well just fix the places where we're incompatible. Afaik, that is just the `DROP INDEX` syntax in a couple of places.
Note there are also occurrences in the reverse migrations, which I haven't bothered to fix. Seeing as they're not invoked in normal running and need to be manually uncommented before running anyway, it seems reasonable for them to be manually edited if anyone needs to do so.
> chore(db): use mariadb-friendly drop index syntax

- db-server/test/fake.js
Fixes #428.
I happened to be running a local MySQL with latin1 as the default encoding, and the sporadic token-pruning test failure from #428 triggered every single time on my machine.  It turns out that this test was trying to create an account for an email address of the form `<16 random bytes>@example.com`.
My theory is that on our CI machines where MySQL is using utf8 by default, such a string can *almost always* be stored correctly and allow the tests to pass.  But if the 16 random bytes happen to produce, say, the surrogate pair encoding of an emoji, then MySQL will do its fun utf8-versus-utf8mb4 thing and truncate the string, triggering a strict-mode failure.
On my local machine with latin1 encoding, such a string can *almost never* be stored correctly and hence I was able to …
> fix(tests): Don't put binary data into fake email addresses.

- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-091-092.sql
- lib/db/schema/patch-092-091.sql
Fixes #438 
Connects to https://github.com/mozilla/fxa-auth-db-mysql/issues/440
Opted to pull these two issues into one migration since they were both fairly small and not to introduce too much headache with merge conflicts for https://github.com/mozilla/fxa-auth-db-mysql/pull/436.
First commit:
Removes the `LOWER(uid)` from the `account_` stored procedure since it doesn't really change the query.
Second commit:
From https://github.com/mozilla/fxa-auth-db-mysql/issues/440, it specifies the charact set for `inEmail` as utf8 for the `accountRecord_` procedure. It also re enables coalescing in SQL rather than in code.
> fix(account): don't use `LOWER(uid)` in account query, update `accountRecord`

- db-server/lib/error.js
- db-server/test/backend/db_tests.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-092-093.sql
- lib/db/schema/patch-093-092.sql
Fixes #411 
This PR removes the use of `ROW_COUNT()` from our remaining procedures. Below is a summary of our use of `ROW_COUNT()` and when they were fixed.
- setPrimaryEmail
- Fixed in setPrimaryEmail_4 (this PR)
- consumeRecoveryCode
- Fixed in consumeRecoveryCode_3 (this PR)
- verifyTokensWithMethod
- Fixed in verifyTokensWithMethod_3
- deleteEmail
- Fixed in deleteEmail_2
- verifyTokenCode
- Fixed in verifyTokenCode_2
- verifyEmail
- Fixed in verifyEmail_4
> fix(query): remove `ROW_COUNT()` from remaining procedures

- db-server/test/backend/db_tests.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-093-094.sql
- lib/db/schema/patch-094-093.sql
With the introduction of https://github.com/mozilla/fxa-auth-db-mysql/pull/445, I caused some breakage in set primary email. That PR added the check to ensure the new primary email is verified in db-server before setting it. The goal was to eventually remove it from the [auth-server](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/emails.js#L763).
However, the new procedure isn't quite working as expected and content-server tests are failing. To help unblock content-server, this PR removes the check from the db-server and uses the auth-server check.
> fix(query): update set primary email query to not check if email is verified

- npm-shrinkwrap.json
Ran shrinkwrap to get the latest deps, fixes https://github.com/mozilla/fxa-auth-db-mysql/pull/469#issuecomment-452550967.
Target train-128, will create a point release after merge.
> chore(deps): reshrink to get ramda deps

- grunttasks/eslint.js
- scripts/createAccounts.js
I wrote this script a while ago to create account rows for db migration testing. Might as well check it in.
It's extracted from other test code. It could be more efficient but it's good enough for its purpose.
r? - @mozilla/fxa-devs
> fix(test): add a test script to add account rows

- .travis.yml
- lib/db/util.js
- npm-shrinkwrap.json
- package.json
This came up in a meeting last week so I took a moment to dig into it. The approach I took was to move `scrypt-hash` to an optional dependency then use `crypto.scrypt` as a fallback implementation. The magic number math was required to prevent `memory limit exceeded` errors occurring with our value for `N`.
Equivalent PR for the auth server is also incoming, using the same approach.
> fix(tests): pass tests in node 10

- .circleci/config.yml
- .travis.yml
- Dockerfile-build
- npm-shrinkwrap.json
- package.json
Fixes #476.
Updates the dockerfile and circle to use node 10 images. Also updates nyc because of the handlebars nsp advisory. Didn't get any problems updating, so not sure what I did differently to @shane-tomlinson after he mentioned something in the meeting yesterday.
I figured we could try this for train 131? Otherwise there's nothing in master that merits tagging a new release.
> chore(deploy): upgrade to node 10

- db-server/index.js
- db-server/test/backend/remote.js
- docs/API.md
The default `sessionToken` route now returns device info all the time, this this extra route is unnecessary.  Goes with https://github.com/mozilla/fxa-auth-server/pull/2934, and IIRC we can ship them in the same train due to the way that auth and auth-db are always deployed as a pair.
> chore(routes): Remove last vestiges of `sessionWithDevice` route.

- db-server/test/backend/db_tests.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-094-095.sql
- lib/db/schema/patch-095-094.sql
Fixes #481.
This undoes the backout in https://github.com/mozilla/fxa-auth-db-mysql/pull/417, and adds some very minimal code for reading the new `keysChangedAt` column which was added as part of the same production migration.  The `keysChangedAt` column will always be null for now, until we add code in the auth-server to know when to set it.
> feat(account): Add `profileChangedAt` and `keysChangedAt` columns

- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-095-096.sql
- lib/db/schema/patch-096-095.sql
Per https://github.com/mozilla/fxa-auth-db-mysql/pull/483/files#r265148343 this is a preparatory migration that should allow us to fix https://github.com/mozilla/fxa-auth-db-mysql/issues/485 without missing any deletes.
This will need to be deployed before #483 in order to get the desired affect.
> chore(devices): Add explicit deletes to replace `ON DELETE CASCADE`.

- db-server/index.js
- db-server/test/backend/db_tests.js
- db-server/test/backend/remote.js
- db-server/test/fake.js
- lib/db/mem.js
- lib/db/mysql.js
- lib/db/patch.js
- lib/db/schema/patch-096-097.sql
- lib/db/schema/patch-097-096.sql
~~Extremely WIP, but sharing early for context.  PR is currently targetting #482 since it builds on that db migration chain, we'll have to get that merged and rebase this PR before we can merge to master.~~
~~This is now ready for testing and review, but I'm going to leave it as "draft" until we've tried it end-to-end with the corresponding auth-server changes.~~
This is ready for merge, but IIUC we want to do it as a point-release after #492 has hit production.
Fixes #480, Fixes #485; /cc @vladikoff @shane-tomlinson @eoger
> feat(devices): Add ability to associate a device record with a refesh token
