db/mysql.js, db/patch.js, db/schema/patch-007-008.sql, db/schema/patch-008-007.sql, npm-shrinkwrap.json, package.json
* Add `lockAccount`, `unlockAccount`, and `unlockCode` db functions.
* Add a new `lockedAt` column to the `accounts` table.
* Update `emailRecord` and `account` to return `lockedAt`
* Add `accountUnlockCodes` table to keep track of account unlock codes
Pieced together from:
* https://github.com/mozilla/fxa-auth-db-server/pull/91
* https://github.com/chilts/fxa-auth-db-server/pull/2
* My own additions.
Goes along with:
* https://github.com/mozilla/fxa-auth-db-server/pull/123
* https://github.com/mozilla/fxa-auth-db-mem/pull/11
* https://github.com/mozilla/fxa-auth-mailer/pull/23
* https://github.com/mozilla/fxa-js-client/pull/141
* https://github.com/mozilla/fxa-content-server/pull/1806
* https://github.com/mozilla/fxa-auth-server/pull/867
=> feat: Account locked feature.

notifier.js, npm-shrinkwrap.json, package.json
This will allow us to use the json secret key from the auth-server directly for the notifier.
r? @rfk
=> allow json secret key file

package.json
Things like homepage, bugs and keywords.
=> chore(package.json): add extra fields related to the repo

npm-shrinkwrap.json
My life is one never ending series of fun!
=> chore(shrinkwrap): update shrinkwrap

lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-010-011.sql, lib/db/schema/patch-011-010.sql
Part of https://github.com/mozilla/fxa-auth-db-server/issues/88
=> Added checkPassword_1 stored procedure

lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-012-013.sql, lib/db/schema/patch-013-012.sql
=> feat(api): Return the account email address on passwordChangeToken

lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-013-014.sql, lib/db/schema/patch-014-013.sql
Fixes https://github.com/mozilla/fxa-auth-db-mysql/issues/47
=> refactor(db): remove verifyHash from responses

config/config.js
Ref: https://github.com/mozilla/fxa-oauth-server/issues/296
=> refactor(config): Use human-readable duration values in config

fxa-auth-db-server/test/backend/db_tests.js
is this sufficient? - r? @dannycoates
=> fix(tests): used a randomized openid url, fixes #91

bin/metrics.js, test/local/metrics_tests.js
=> fix(metrics): append delimiter to metrics output

.eslintrc, lib/db/mem.js
Fixes #95 
@jrgm 
@rfk 
@vladikoff
=> chore(eslint): change complexity rule

scripts/metrics-perf.sh
As per https://github.com/mozilla/fxa-auth-db-mysql/issues/81#issuecomment-138139305.
=> chore(metrics): report latency in performance tests

docs/API.md, fxa-auth-db-server/docs/API.md, fxa-auth-db-server/index.js, fxa-auth-db-server/test/backend/db_tests.js, fxa-auth-db-server/test/backend/remote.js, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-016-017.sql, lib/db/schema/patch-017-016.sql
Fixes #98, although technically that issue is assigned to @dannycoates.
I figured I'd open this PR because I needed to implement it locally to test my work on https://github.com/mozilla/fxa-auth-server/issues/1038 anyway. Go ahead and close this though, if something better/different is on its way.
=> feat(db): add endpoint to return a user's sessions

fxa-auth-db-server/package.json
=> Update package metadata for stand-alone server lib.

fxa-auth-db-server/index.js, fxa-auth-db-server/test/backend/remote.js, fxa-auth-db-server/test/fake.js
Spotted this while testing out the device registration stuff, there's a mismatched parameter name on the `upsertDevice` route.
@dannycoates or @rfk, r?
=> fix(server): fix bad route parameter name

docs/API.md, fxa-auth-db-server/index.js, fxa-auth-db-server/test/backend/db_tests.js, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-020-021.sql, lib/db/schema/patch-021-020.sql
Supports https://github.com/mozilla/fxa-auth-server/pull/1168
=> /sessionToken/:id/device endpoint

bin/server.js, lib/db/mysql.js, test/local/mysql_tests.js
A little info of interest.
r? - @philbooth @rfk
=> fix(logging): log connection config and charset info at startup

.travis.yml
=> chore(travis): drop node 0.12 support

docs/API.md, fxa-auth-db-server/index.js, fxa-auth-db-server/test/backend/db_tests.js, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-025-026.sql, lib/db/schema/patch-026-025.sql
Connects to https://github.com/mozilla/fxa/issues/138
=> feat(reminders): add verification reminders

npm-shrinkwrap.json, package.json
=> fix(deps): update prod dependencies

npm-shrinkwrap.json, package.json
@vbudhram r?
This fixes nsp issues with the old request version
=> chore(deps): update to latest request and sinon

fxa-auth-db-server/docs/API.md, fxa-auth-db-server/index.js, fxa-auth-db-server/test/backend/db_tests.js, fxa-auth-db-server/test/backend/remote.js, fxa-auth-db-server/test/fake.js, lib/db/mem.js, lib/db/mysql.js
With signin confirmation and email caphta we have more targeted
meant to keep bad people at bay while minimizing friction for valid
users, account lockout no longer seems particularly elegant.
fixes #146
Should be merged after https://github.com/mozilla/fxa-auth-server/pull/1360
=> feat: Remove account lockout

fxa-auth-db-server/index.js, fxa-auth-db-server/test/backend/db_tests.js, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-027-028.sql, lib/db/schema/patch-028-027.sql
=> refactor(db): remove openId

scripts/populate-session-tokens.js
Not sure whether anyone else has used this script or might benefit from it in the future, but it's what I use when I need a load of accounts and session tokens to run performance tests against.
Before this change, it didn't create any device records. With this change, it does.
@vbudhram, r?
=> feat(scripts): add device records to the populate script

scripts/populate-session-tokens.js
=> fix(scripts): add process.exit to populate script

fxa-auth-db-server/index.js, fxa-auth-db-server/test/backend/db_tests.js, fxa-auth-db-server/test/backend/remote.js, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-034-035.sql, lib/db/schema/patch-035-034.sql
Before merging, still needs to check a deadline, similar to password reset tokens.
=> feat(unblock): add unblockCode support

lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-037-038.sql, lib/db/schema/patch-038-037.sql
=> chore(securityEvents): Stop writing to the `securityEvents.tokenId` column

fxa-auth-db-server/index.js, fxa-auth-db-server/lib/bufferize.js, fxa-auth-db-server/test/backend/remote.js, fxa-auth-db-server/test/local/bufferize.js
Reverts mozilla/fxa-auth-db-mysql#182
=> revert(bufferize): Only bufferize params we explicitly want as buffers.

lib/db/patch.js, lib/db/schema/patch-038-039.sql, lib/db/schema/patch-039-038.sql
Fixes #178, Fixes #181; @mozilla/fxa-devs r?
=> fix(schema): Complete final phase of several previous migrations.

npm-shrinkwrap.json, package.json
=> chore(deps): add new shrinkwrap command

fxa-auth-db-server/test/backend/db_tests.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-039-040.sql, lib/db/schema/patch-040-039.sql
=> fix(reminders): adjust mysql procedures

fxa-auth-db-server/docs/API.md, fxa-auth-db-server/index.js, fxa-auth-db-server/test/backend/db_tests.js, fxa-auth-db-server/test/backend/remote.js, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-041-042.sql, lib/db/schema/patch-042-041.sql
Connects to mozilla/fxa-auth-server#1651
=> feat(tokens): get the device associated with a tokenVerificationId

config/config.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-042-043.sql, lib/db/schema/patch-043-042.sql, test/local/prune_tokens.js
=> feat(tokens): add prune token maxAge and update pruning

fxa-auth-db-server/test/backend/db_tests.js, fxa-auth-db-server/test/backend/remote.js, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-044-045.sql, lib/db/schema/patch-045-044.sql
Connects to mozilla/fxa-content-server#4585
=> feat(sessions): update the sessions query to include device information

fxa-auth-db-server/index.js, fxa-auth-db-server/package.json, npm-shrinkwrap.json
=> fix(security): escape json output

config/config.js
=> feat(tokens): prune tokens older than 3 months

fxa-auth-db-server/test/backend/db_tests.js, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-051-052.sql, lib/db/schema/patch-052-051.sql
This updates all mysql queries to use the emails table over the account table.
Part 3 of https://github.com/mozilla/fxa-auth-db-mysql/issues/244
=> feat(email): Update procedures to use email table

.eslintrc, Dockerfile-build, fxa-auth-db-server/test/.eslintrc, fxa-auth-db-server/test/backend/db_tests.js, fxa-auth-db-server/test/backend/remote.js, fxa-auth-db-server/test/local/bufferize.js, lib/db/mem.js, lib/db/mysql.js, npm-shrinkwrap.json, package.json, scripts/.eslintrc, scripts/analyze-mx-stats.js
Fixes https://github.com/mozilla/fxa-auth-db-mysql/issues/216
=> chore(eslint): update to latest eslint

CHANGELOG.md, fxa-auth-db-server/test/backend/db_tests.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-051-052.sql, lib/db/schema/patch-052-051.sql, lib/db/schema/patch-052-053.sql, lib/db/schema/patch-053-052.sql, lib/db/schema/patch-053-054.sql, lib/db/schema/patch-054-053.sql, lib/db/schema/patch-054-055.sql, lib/db/schema/patch-055-054.sql, lib/db/schema/patch-055-056.sql, lib/db/schema/patch-056-055.sql, npm-shrinkwrap.json, package.json
Trains 89.1 and 89.3 contained updates to the `accountEmails` and `forgotPasswordVerified`. This PR uplifts those changes and increments all the preceding migrations.
=> Train 89 uplift

docs/API.md, fxa-auth-db-server/index.js, fxa-auth-db-server/test/backend/db_tests.js, fxa-auth-db-server/test/backend/remote.js, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-056-057.sql, lib/db/schema/patch-057-056.sql
Adds support for changing email.
Fixes https://github.com/mozilla/fxa-auth-db-mysql/issues/236
=> feat(email): Add change email

lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-061-062.sql, lib/db/schema/patch-062-061.sql, test/local/mysql_tests.js
Connects to https://github.com/mozilla/fxa-auth-db-mysql/issues/229
=> feat(db): add utf8mb4 support

lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-064-065.sql, lib/db/schema/patch-065-064.sql, scripts/migration.sh
=> fix(mysql): update all device procedures to use utf8mb4

Dockerfile-build
=> fix(newrelic): newrelic native requires make, python, gyp, c++; update node 6.12.0

bin/server.js, config/config.js, npm-shrinkwrap.json, package.json
Fixes https://github.com/mozilla/fxa-auth-db-mysql/issues/288
=> feat(logs): add Sentry for errors

scripts/migration.sh
Realised this was missing while reviewing #295.
=> fix(scripts): add SET NAMES to reverse migration boilerplate

db-server/test/backend/remote.js, db-server/test/fake.js, lib/db/mem.js
The PR matches the functionality of the mysql `verifyTokenCode` operation and verifies both session and keyFetch tokens. If a valid `tokenCode` is found, verifies the session and keyFetchToken matching its `tokenVerificationId`.
Connects to https://github.com/mozilla/fxa-content-server/issues/5886
=> fix(token): Fix mem verifyTokenCode

db-server/index.js, db-server/test/backend/db_tests.js, db-server/test/backend/remote.js, db-server/test/fake.js, docs/API.md, docs/DB_API.md, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-070-071.sql, lib/db/schema/patch-071-070.sql
For the first phase of TOTP, this PR adds all procedures and endpoints needed to create, get and delete a user's token. The API definition can be found in #300.
Fixes #300
=> feat(totp): Add totp management api

npm-shrinkwrap.json, package.json
=> chore(deps): update deps, fix nsp

db-server/index.js, db-server/test/backend/db_tests.js, db-server/test/backend/remote.js, docs/API.md, docs/DB_API.md, lib/db/mem.js, lib/db/mysql.js
This PR fixes #306 and will hopefully simplify https://github.com/mozilla/fxa-auth-db-mysql/pull/309.
=> chore(tests): remove `sessionToken` and `sessionTokenWithVerification`

db-server/index.js, db-server/test/backend/remote.js, docs/API.md
Missed review comments from https://github.com/mozilla/fxa-auth-db-mysql/pull/309.
=> feat(totp): vlad updates for totp

bin/db_patcher.js, config/config.js, lib/constants.js, lib/db/mysql.js, test/local/constants_test.js, test/local/metrics_tests.js, test/local/mysql_tests.js
Made changes in config and test files.
=> Fixes issue #290 Remove database configuration option, hardcode 'fxa' 

Dockerfile-build
Ref https://github.com/mozilla/fxa-auth-server/pull/2353
=> feat(node): update to node v6.13.1

db-server/index.js, db-server/lib/bufferize.js, db-server/test/backend/db_tests.js, db-server/test/local/bufferize.js, lib/db/mem.js, lib/db/mysql.js
Changes done :
1. Added new function in bufferize to utf8 encode the hex email parameter
2. Modified unit test for bufferize to handle new function
3. Removed utf8 conversion from both database files
4. Modified local db tests to pass unhexed email parameter
=> chore(api): #318 remove bufferization from db layer

.nsprc, npm-shrinkwrap.json, package.json
=> Update newrelic version

.nsprc, db-server/index.js, db-server/lib/safeJsonFormatter.js, db-server/test/client-then.js, db-server/test/local/safeJsonFormatter.js, npm-shrinkwrap.json, package.json
=> fix(deps): update restify and mysql

db-server/index.js, db-server/test/backend/db_tests.js, db-server/test/backend/remote.js, docs/API.md, docs/DB_API.md, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-080-081.sql, lib/db/schema/patch-081-080.sql, npm-shrinkwrap.json
=> feat(recovery): Add initial account recovery key support

CHANGELOG.md, Dockerfile-build, npm-shrinkwrap.json, package.json
=> chore(merge): Merge train-114 into master

CHANGELOG.md, npm-shrinkwrap.json, package.json
This appears to actually just tag a merge commit from the previous release, but it seemed worthwhile for consistency.
=> Release v1.115.0

db-server/test/backend/db_tests.js, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-084-085.sql, lib/db/schema/patch-085-084.sql
Fixes #384, based on analysis from https://github.com/mozilla/fxa-auth-db-mysql/issues/384#issuecomment-414565389.
I believe we plan to do this as a point release of train-119, but since there aren't any other commits on master yet, perhaps it's simpler to land it on master and then cut the point release from there?
@philbooth @jrgm r?
=> fix(devices): Reinstate device commands, with performance fixes.

db-server/index.js, db-server/lib/error.js, db-server/test/backend/db_tests.js, db-server/test/backend/remote.js, docs/API.md, docs/DB_API.md, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-085-086.sql, lib/db/schema/patch-086-085.sql, lib/db/util.js
Fixes #366 
~~WIP, need to confirm how many users enabled recovery key in production.~~
Confirmed that no one has enabled this in production yet.
=> fix(recovery): hash recovery key id

db-server/test/backend/db_tests.js, lib/db/mem.js, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-087-088.sql, lib/db/schema/patch-088-087.sql, package.json
Connects to https://github.com/mozilla/fxa-auth-db-mysql/issues/400
=> fix(account): delete recovery codes/keys, security events on account delete

lib/db/patch.js, lib/db/schema/patch-088-089.sql, lib/db/schema/patch-089-088.sql
=> fix(performance): Add index for scanning signinCodes by uid.

CHANGELOG.md, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-087-088.sql, lib/db/schema/patch-088-087.sql
This PR uplifts train-121 to train-122. It appends migration from https://github.com/mozilla/fxa-auth-db-mysql/pull/410 as migration 88.
=> Train 122 lift 121

CHANGELOG.md, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-089-090.sql, lib/db/schema/patch-090-089.sql
Uplifts train-122 to train-123 and makes the replication fixes the last migration on the train, ref https://github.com/mozilla/fxa-auth-db-mysql/pull/412#issuecomment-431235224
=> Train 123 uplift 122

CHANGELOG.md, lib/db/mysql.js, lib/db/patch.js, lib/db/schema/patch-089-090.sql, lib/db/schema/patch-090-089.sql, npm-shrinkwrap.json, package.json
Since https://github.com/mozilla/fxa-auth-db-mysql/pull/415 was created through the Github UI I couldn't use `--amend` to clean up the changelog. This PR has the requested changes.
=> Master uplift train 123 v2

lib/db/mysql.js, lib/db/schema/patch-091-090.sql
Connects to https://github.com/mozilla/fxa-content-server/issues/6655.  This reverts back to the previous `accountRecord_2` SP in order to unblock train-123.  @jrgm r?
=> fix(accountRecord): Rollback `accountRecord_4` due to unexplained performance issues

CHANGELOG.md, npm-shrinkwrap.json, package.json
Only just noticed I needn't have cut this, looks like nothing's happened on `master` other than merges from the train-123 branch. But I've started now so...
=> Merge train-124 into master

npm-shrinkwrap.json, package.json
Connects to https://github.com/mozilla/fxa/issues/325
=> feat(npm): update shrink script
